### ISSUE TITLE
Empty objects attached to armature cause Bake to fail

### ISSUE THREAD

**Issue by feilen** [absolute-quantum/cats-blender-plugin#241]
See title, 
- ~~meshes without shape keys cause an exception (which we should just ignore them)~~ fixed, thanks @redstrate 
- empty objects cause an exception when trying to bake (when we should just copy them)

**Comment by Onebeautifulgreek** [comment]
Would you please stop sending me notifications I don’t care to know what you want to tell me so just back off I’m done I’m not gonna say it again
Would you please stop sending me notifications I don’t care to know what you want to tell me so just back off I’m done I’m not gonna say it again

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by feilen** [comment]
Uh, the only way you'd be getting notifications is if you're subscribed to this repo. Hit 'Unwatch' above.
