### ISSUE TITLE
'Join Meshes' should create shape keys that 'hide' meshes by shrinking them down to nothing

### ISSUE THREAD

**Issue by feilen** [absolute-quantum/cats-blender-plugin#250]
See title. Many creators use different meshes as a way to create toggleable props for their characters, but doing so increases the material slots and total drawcalls of the end result. Making Join Meshes throw some extra shape keys in to 'disable' them (without actually hiding the geometry) would work better for VRChat's performance pain points.

Additionally, any mesh that's currently hidden when joined could set the 'disable' key to 1.0 in the result, by default. (though, would that be confusing? It could result in users confused that they have a bunch of extra geometry they can't find)

**Comment by GameKuchen** [comment]
Was this ever added?

**Comment by imagitama** [comment]
> Was this ever added?

Not yet in the development branch. :(
