### ISSUE TITLE
[needupdate]2.9.3 error PropertyDeferred

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [absolute-quantum/cats-blender-plugin#262]
Task failed

Python: Traceback (most recent call last):
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 98, in execute
    for f in self.files:
TypeError: '_PropertyDeferred' object is not iterable

location: <unknown location>:-1

**Comment by Lyriati** [comment]
Seems like the latest blender update has broken cats

**Comment by 1C0D** [comment]
it's because a property in an operator has an "=" instead of a ":"

**Comment by hemantcpt** [comment]
Hi,  
My name is hemant  in my PC there is same problem but I  install the latest version of blender 2.93.4 and install the addon in blender to start the lighting in my project then its crash the file..

Python: Traceback (most recent call last):
  File "C:\Users\Hemant\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\pro_lighting_studio\pl_studio_props.py", line 1802, in execute
    paths = [os.path.join(folder, name.name)
TypeError: '_PropertyDeferred' object is not iterable

location: <unknown location>:-1

**Comment by Marcus-Zhu** [comment]
Hi hemantcpt,

Like 1C0D said, changing line 1798 from "files =" to "files :" in pl_studio_props.py will solve this error.
