### ISSUE TITLE
'Multiply_add not found' error when baking model

### ISSUE THREAD

**Issue by refractslight** [absolute-quantum/cats-blender-plugin#265]
In Blender 2.80 with the latest download (as of this post) and with development download: I receive the following traceback when trying to bake my model:
```
Baking normal for objects: Body
Info: Baking map saved to internal image, save it externally or pack it
Traceback (most recent call last):
  File "C:\Users\NAME\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 357, in execute
    self.perform_bake(context)
  File "C:\Users\NAME\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 772, in perform_bake
    multiplytexnode.operation = "MULTIPLY_ADD"
TypeError: bpy_struct: item.attr = val: enum "MULTIPLY_ADD" not found in ('ADD', 'SUBTRACT', 'MULTIPLY', 'DIVIDE', 'POWER', 'LOGARITHM', 'SQRT', 'ABSOLUTE', 'MINIMUM', 'MAXIMUM', 'LESS_THAN', 'GREATER_THAN', 'ROUND', 'FLOOR', 'CEIL', 'FRACT', 'MODULO', 'SINE', 'COSINE', 'TANGENT', 'ARCSINE', 'ARCCOSINE', 'ARCTANGENT', 'ARCTAN2')

location: <unknown location>:-1

location: <unknown location>:-1

```
The model comes out white.

I've installed anaconda to ensure I have numpy installed.

Any ideas of what I can do?

**Comment by feilen** [comment]
I believe the minimum supported is 2.83?

**Comment by soozical** [comment]
I tried with newest release of blender, and while I don't get the traceback, it still produces a gray avatar with broken atlases, which I know is not this github issue. I'd love any suggestions, though.

**Comment by feilen** [comment]
Would you mind adding a screenshot of what your bake settings are?

(also, if you aren't already, try the development version)
