### ISSUE TITLE
create 52 shapekeys using visemes shapekey creation method?

### ISSUE THREAD

**Issue by krigeta** [absolute-quantum/cats-blender-plugin#287]
Hello, as we can create mouth shapekeys by making only three shapekeys, is it possible to do this task to make shapekeys by using some shapekeys to generate ARKit 52 shapekeys?

**Comment by Darkblader24** [comment]
Yes that would definitely be awesome, but seems very difficult. I will add it to the todo list

**Comment by impactcolor** [comment]
What about the opposite making Viseme shape keys from the ark kit 52 shapekeys?
