### ISSUE TITLE
Cats translate error

### ISSUE THREAD

**Issue by AmanosamaCiel** [absolute-quantum/cats-blender-plugin#295]
When i try to use the "translate all" button on a mmd model, it says "It looks like you got banned from google translator" which makes it unable to translate.

**Comment by Arcticgamez** [comment]
getting this error msg as well

**Comment by HLVNHLV** [comment]
same

**Comment by Jason9811** [comment]
Also the same, updated everything to make sure as well and not banned from Google Translate as I can still use it!

**Comment by Pockyman1** [comment]
yup ditto there also ggetting that same error

**Comment by CaelThunderwing** [comment]
getting it here on August 2nd

**Comment by Pockyman1** [comment]
Also still getting this same Error too on my end

**Comment by MistressPlague** [comment]
I am still getting this error.

**Comment by HajiyevEl** [comment]
@Darkblader24 
Same issue, can't translate

**Comment by Darkblader24** [comment]
This is fixed in the dev version, you can install it via the Settings & Updates panel
