### ISSUE TITLE
VRChat Avatar Separate by Loose Parts crashes Blender 2.83.16

### ISSUE THREAD

**Issue by Emberrss** [absolute-quantum/cats-blender-plugin#314]
I was told Blender 2.8 is much better overall than 2.79b, so I upgraded and now I don't want to go back to 2.79, but Blender keeps crashing using the CATS plugin and I'm not sure why. This started a few months ago with avatar creation so I stopped for a while, though I don't remember what options I had used that caused crashing. Just started again today and I'm still getting crashing issues, this time with Separate by Loose Parts. 

I had loaded an example FBX I cleaned up from a DeviantArt PMX file (removed accessories and some clothing that stuck out), along with the original PMX using Blender 2.83.16 and CATS 0.19, Fix Model, then Separate Loose Parts. The FBX version will immediately close Blender with no errors or crash logs, and the PMX will process for a few seconds before closing Blender again with no errors or crash logs.

**Comment by Gusher** [comment]
Did you try fbx versions from 2010 - 2014 ? ..usually the older fbx versions should solve issues like that...

**Comment by Darkblader24** [comment]
Sometimes Blender can be overwhelmed by the amount of meshes generated by Sepatae By Loose Parts. To reduce this issue, you should split up your mesh beforehand, for example by using Separate By Materials and then only separate the meshes you actually want to separate
