### ISSUE TITLE
Baking an avatar for quest failure: key ""CATS UV" not found"

### ISSUE THREAD

**Issue by joybod** [absolute-quantum/cats-blender-plugin#315]
Python: Traceback (most recent call last):
  File "C:\Users\joybo\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-19-0\tools\bake.py", line 434, in execute
    self.perform_bake(context)
  File "C:\Users\joybo\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-0-19-0\tools\bake.py", line 595, in perform_bake
    obj.data.uv_layers.active = obj.data.uv_layers[layer]
KeyError: 'bpy_prop_collection[key]: key "CATS UV" not found'

location: <unknown location>:-1

![image](https://user-images.githubusercontent.com/25726397/136879045-e2abbd87-ecec-4b4a-a832-961479139476.png)

**Comment by Stiklore** [comment]
Press Fix Model in Cats. That fixes it

**Comment by feilen** [comment]
Any news on this?

**Comment by ashenbeauty** [comment]
I'm actually encountering this exact issue when attempting to bake my model. I have been unable to find any info online about it, either. Can confirm that the same issue occurs on the dev build of CATS as well.

```
Python: Traceback (most recent call last):
  File "C:\Users\Cailan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 384, in execute
    self.perform_bake(context)
  File "C:\Users\Cailan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 539, in perform_bake
    obj.data.uv_layers.active = obj.data.uv_layers[layer]
KeyError: 'bpy_prop_collection[key]: key "CATS UV" not found'

location: <unknown location>:-1
```

**Comment by feilen** [comment]
Wamp. If you PM me your .blend on discord I can try to take a look. How recent is your dev version?

**Comment by ashenbeauty** [comment]
The dev version I was using was the most recent, as I specifically installed it as a troubleshooting step. 

However, I actually just found out what seems to cause the error, just through toying around- it seems having multiple UV Maps on a single mesh will cause it to wig out when building the new UVMap. Deleting all of my old ones solved the issue instantly.

Edit: I assume that this is either caused by the plugin expecting a specific name, or by it simply not expecting multiple maps on a single mesh.

**Comment by feilen** [comment]
Ahhh... so I just discovered Blender has a hard limit on per-mesh UVMaps. It tops out at 8, and CATS Bake uses 2 for itself. Not something we can totally fix automatically, but I will add a warning in the UI and have the bake button greyed out if you have any objects with >6 UVMaps. Thanks for the help!

**Comment by feilen** [comment]
I've added a warning in the UI if you have greater than 6 uvmaps (we need up to two for baking) and try to discard unused uvmaps earlier in the bake process. Hopefully that solves it once and for all!
