### ISSUE TITLE
Baking an Avatar for Quest error (Blender 2.93.0, CATS plugin 0.19.1-dev)

### ISSUE THREAD

**Issue by SerenRV** [absolute-quantum/cats-blender-plugin#316]
When attempting to bake an Avatar using the Quest settings (with the addition of Ambient Occlusion + Set eyes to full brightness and Tris count set to 15000), the following error appears and nothing else happens: 

Python: Traceback (most recent call last):
  File "C:\Users\Elija\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 414, in execute
    render_device_tmp = context.scene.cycles.device
AttributeError: 'Scene' object has no attribute 'cycles'

location: <unknown location>:-1

Yes, even with the default 7500 Tris count this still occurs. If I use 0.19.0 instead, the error changes to specify line 363 instead of line 414...and that is pretty much it. Picture attached shows exact bake settings used for convenience.

![Problem Screenshot](https://user-images.githubusercontent.com/94144926/141375014-60c68d25-efa7-48ff-8b30-059aad5a6245.png)

**Comment by feilen** [comment]
You might have something rather odd in your scene. You wouldn't by chance have a weird build of blender would you? If not, would you mind attaching (or pming) your .blend with all the textures packed into it?

**Comment by SerenRV** [comment]
I do not think I do, but if so here is the .blend and texture atlas.

https://mega.nz/file/PRwh2AoY#US_xilGb5f047fTObL78s3E2S2GEWgjOHHNluhaUIxs (.blend here, had to link it via Mega due to no file type support...)

![Atlas_63449](https://user-images.githubusercontent.com/94144926/141389090-b67c1de1-31a6-40cb-b82b-5476339b3607.png)

**Comment by SerenRV** [comment]
Hey! I am here to say I was able to resolve this problem (with a friend's assistance) simply by toggling the Cycles add-on and toggling bake with Cycles as the Render. Sorry and thanks for helping anyways! Hopefully this is of any use to anyone else.

**Comment by feilen** [comment]
Wasn't aware you could even turn off Cycles, but that would definitely be it!
