### ISSUE TITLE
Blender 3.0 breaks everything and really really quickly.

### ISSUE THREAD

**Issue by NightlyDreams** [absolute-quantum/cats-blender-plugin#341]
I had moved to 3.0 for my world creation stuff for vrchat and because the tools were way better for it. But i decided to go back to a project i had open on 2.9 and it worked that was a avatar model. Except for a small few errors. So re opened a new project and clicked fix model and it says there was a error and shut down my blender. Now i cant do anything with cats it just shuts down blender if i click any of its buttons.

And i would just revert to blender 2.9 but i do not have it anymore and Blender website will not allow me to down load it. I can only down load 3.0 from blenders site. So now i have a project that i spent so much time on that i can't touch as it will just close blender with a error.

**Comment by NightlyDreams** [comment]
![Screenshot_81](https://user-images.githubusercontent.com/97270588/148489139-635868ea-9ad9-4175-8f4d-9d7d369a5b88.png)

This is what happens Dev or normal cats

**Comment by 989onan** [comment]
Fixed in commit c01cfffbaf68104001324f09d5c5f758266e40ac

**Comment by Darkblader24** [comment]
And merged 👍
