### ISSUE TITLE
Shotariya's Atlas Generator does not exist.

### ISSUE THREAD

**Issue by aytimothy** [absolute-quantum/cats-blender-plugin#344]
Under Optimization, going to Atlas, and if you're on a fresh install without the material combiner...

![image](https://user-images.githubusercontent.com/7418834/148641268-689cac65-19e5-43f5-b1d1-09dfe913046a.png)

Clicking the "Download Material Combiner" button opens [this link](https://vrcat.club/threads/material-combiner-blender-addon-2-1-1-2.2255/). However, it does not exist anymore.

![image](https://user-images.githubusercontent.com/7418834/148641228-27f6a6fd-2292-41c8-b088-03074955a876.png)

Visiting the [root domain](https://vrcat.club) seems to redirect to [VRChat Ask](https://ask.vrchat.com).

**Comment by aytimothy** [comment]
It seems to have been moved to [Patreon](https://www.patreon.com/shotariya)

**Comment by Darkblader24** [comment]
Thank you, I updated the link 👍
