### ISSUE TITLE
Combine Same Materials Breaks Avatar textures

### ISSUE THREAD

**Issue by ItzNotTheMagicOwl** [absolute-quantum/cats-blender-plugin#354]
**Before**
![image](https://user-images.githubusercontent.com/84865102/150645687-628e15a7-2b2b-4467-90b1-42befc6ec26b.png)
**After**
![image](https://user-images.githubusercontent.com/84865102/150645702-c3f9b5e7-7e54-432a-b571-a48c34d084f7.png)

I'm unsure why this happens and is their anyway to fix?

**Comment by ItzNotTheMagicOwl** [comment]
i fix it

**Comment by Tellilum** [comment]
How did you fix this? currently having this same issue

**Comment by ItzNotTheMagicOwl** [comment]
> How did you fix this? currently having this same issue

I didn’t use cats and asked for help
