### ISSUE TITLE
Blender 2.93 Bake doesn't work correctly: all the textures are black.

### ISSUE THREAD

**Issue by ilcalmissimo** [absolute-quantum/cats-blender-plugin#363]
I tried using Bake on both the release and development versions and this is the result... both the model in blender and the texture files in the project directory are black (as in, the have no colour whatsoever other than black).

Baking to Quest, by the way. I have a similar issue when baking for desktop though.

<img width="537" alt="Cattura" src="https://user-images.githubusercontent.com/14317993/153766253-c8d3804a-9bb3-4600-97a3-472d2f6f77cd.PNG">

**Comment by ilcalmissimo** [comment]
This is likely a baking issue in general rather than CATS, but I used the "fix model" option for the textures/materials and haven't touched anything else.

**Comment by feilen** [comment]
Are you on the dev version? There's been some major improvements since the last release, including some extra warnings about things that could be going wrong
