### ISSUE TITLE
Issue with Atlas Generator

### ISSUE THREAD

**Issue by nalathethird** [absolute-quantum/cats-blender-plugin#365]
https://vrcat.club/threads/material-combiner-blender-addon-1-1-3.2255/
website no longer responds to install Atlas Combiner
can we get a fixed link?
![image](https://user-images.githubusercontent.com/36301692/154418894-27d9f9ff-12d8-4362-bd98-a3e3ac551963.png)
![image](https://user-images.githubusercontent.com/36301692/154419066-b29657c5-9a2e-483f-bf54-edea1bfaa791.png)

**Comment by 989onan** [comment]
This is coming in the new 1.20 update. We are aware of this issue but thanks!

**Comment by Toys0125** [comment]
@tgrafk12 You can always get the addon directly from the source while they fix it. https://github.com/Grim-es/material-combiner-addon/
