### ISSUE TITLE
"TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" - Function.width expected an int type, not float" (Blender 3.1 incompatibility due to Python version upgrade (no more implicit conversion from float to int))

### ISSUE THREAD

**Issue by Mysteryem** [absolute-quantum/cats-blender-plugin#379]
For info, see the top of the release notes for the Python API: https://wiki.blender.org/wiki/Reference/Release_Notes/3.1/Python_API

All of the usages of `invoke_props_dialog` that have a non integer `width` argument are going to need to have the `width` argument be cast to int or similar.

I don't know if there are other areas affected since you can't get very far without hitting an `invoke_props_dialog` call with a float width.

**Comment by Mysteryem** [comment]
Looks like there's already a pr for fixing this https://github.com/absolute-quantum/cats-blender-plugin/pull/378

**Comment by feilen** [comment]
For anyone experiencing this issue, the fix currently is to either upgrade your CATS to the development version: https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip

Or downgrade your Blender to version 2.93.

**Comment by UnknoOff** [comment]
> For anyone experiencing this issue, the fix currently is to either upgrade your CATS to the development version: https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip
> 
> Or downgrade your Blender to version 2.93.

I want to say thank you for helping to solve this problem. I really appreciate such people!
