### ISSUE TITLE
Transparency does not bake correctly

### ISSUE THREAD

**Issue by Tenshinen** [absolute-quantum/cats-blender-plugin#392]
When baking with transparency, areas that should be entirely opaque are baked with a very slight amount of transparency, ruining all transparency blend modes other than cutout, as the character now becomes slightly transparent.
Example, also happens if transparency is baked as a separate texture:
![image](https://user-images.githubusercontent.com/36275083/159121041-2d5aa23d-07d7-477a-93ad-024ec5153981.png)

**Comment by feilen** [comment]
I've just pushed a potential fix for this, could you give it a shot? (development branch)

**Comment by Tenshinen** [comment]
> I've just pushed a potential fix for this, could you give it a shot? (development branch)

Seems to work great, both separate texture and diffuse alpha transparency are fully working as expected now!

**Comment by feilen** [comment]
Excellent!
