### ISSUE TITLE
CATS fix model not working

### ISSUE THREAD

**Issue by fizziefrogs** [absolute-quantum/cats-blender-plugin#393]
Hello!! Currently I'm having a problem, each time I try to click fix model it seems broken and won't work when I click the wrench next to "fix model" 
![fix model](https://user-images.githubusercontent.com/101947047/159134421-5a4da0da-9686-448c-84a8-d87fcd6e8bc3.png)

**Comment by HisokaMorow044** [comment]
im also dealing with this

**Comment by madalynnaline** [comment]
i also have this issue

**Comment by 989onan** [comment]
https://github.com/absolute-quantum/cats-blender-plugin/issues/385
https://github.com/absolute-quantum/cats-blender-plugin/pull/382

**Comment by feilen** [comment]
Duplicate of #379.
