### ISSUE TITLE
Blender 3.0.1 "One or more of your armature's meshes have rendering disabled" when tring to use Copy and Bake

### ISSUE THREAD

**Issue by CommonStarguy** [absolute-quantum/cats-blender-plugin#397]
Says it in title, trying to bake model's textures to export as vrm and it's just giving me this pop up every time

![image](https://user-images.githubusercontent.com/83615968/159157086-2ef6a63e-d586-4196-8148-b7b046141702.png)

Not sure why, I haven't had any trouble rendering in the past when trying to render in both Eevee and Cycles and none of my meshes in the armature are saying that they're disabled.

**Comment by feilen** [comment]
The render toggle button is hidden by default, to enable it you have to enable it in the scene tree.

https://docs.blender.org/manual/en/2.80/editors/outliner.html

**Comment by CommonStarguy** [comment]
This camera icon, correct? I have it enabled on all of my projects by default, yet I still am getting this popup 
![image](https://user-images.githubusercontent.com/83615968/159187573-ae0c1797-cc6e-4be9-a19e-78e4d01b3aa2.png)

**Comment by feilen** [comment]
Uhh, try the dev version. You may have some stuff parented to your armature thats not visible in the view layer anywhere

**Comment by CommonStarguy** [comment]
For documentation's sake, this showed up on all my materials when I went to the Bake tab. May have to do with the fact that my model is using custom shaders
![image](https://user-images.githubusercontent.com/83615968/159189390-8b6f3c99-2fa5-41df-9f74-d306ebc3d283.png)
As it starts baking, I get this popup 
![image](https://user-images.githubusercontent.com/83615968/159268471-5bbea1af-4d53-430c-89c4-fb9bea05d705.png)
And...
![image](https://user-images.githubusercontent.com/83615968/159189610-cc1700e3-7d4d-4aac-aba0-02ffd2082383.png)
I have no clue what I'm doing wrong
![image](https://user-images.githubusercontent.com/83615968/159189643-543539ee-8f91-4ac1-a7c5-ead414e4ad40.png)
No materials look like they were imported along with the model to Unity

**Comment by feilen** [comment]
'NoneType has no attribute copy' means you have some empty objects in your view_layer that are being picked up. It looks like one is the chest collider... try hiding those in the viewport and baking again

**Comment by CommonStarguy** [comment]
Well, um, now this is happening, is this precedented behavior? 
![image](https://user-images.githubusercontent.com/83615968/159268010-9ae00802-7a08-413e-97ca-33e66c4cf074.png)

What the outliner looks like pre-bake 
![image](https://user-images.githubusercontent.com/83615968/159268075-9ad92d2c-1760-4e98-8d89-907e09cb2772.png)

**Comment by feilen** [comment]
Nope, think that one's a bug.
You should be able to work around it by checking 'metallic' though, I think.

**Comment by CommonStarguy** [comment]
Sorry for the late response, I've been busy the past few days.
With the dev branch update and checking 'metallic' and, this is my result via the preview in Texture Paint
![image](https://user-images.githubusercontent.com/83615968/160014247-45f32d18-782b-4bd5-bd6d-4246c0aed30f.png)
And with materials preview
![image](https://user-images.githubusercontent.com/83615968/160014192-753105f5-3b4b-4099-b045-f46e47f9754d.png)
The CATS Bake (Right) is not nearly as bright as how it's supposed to look (left) and it looks like a lot of the colors are lost. My shaders are not translating into the bake correctly? Also a note, I don't know how to translate these shaders into Unity as it's not a unitypackage, but a custom shader preset meant to emulate the lighting of the game the model is from (star wars: the old republic)
![image](https://user-images.githubusercontent.com/83615968/160014586-6da7cde4-3074-4ba7-817f-8aa2cf366de1.png)
On closer inspection, the textures have become very low res

**Comment by feilen** [comment]
Texture Paint always ends up with solid color, which kinda ends up arbitrary. Can I see a screenshot of all your bake options?

And yeah, depending on your setup texture res can end up very low. The ideal way to mitigate that is with UVPackMaster and/or manually packed islands, but the latest version isn't quite supported yet

**Comment by CommonStarguy** [comment]
Sure thing. 
![image](https://user-images.githubusercontent.com/83615968/160034594-dcd2a3cb-4e43-403d-8263-5b7314b43c34.png)
![image](https://user-images.githubusercontent.com/83615968/160034625-a20c3339-6736-409b-89b1-63f0f2a9041c.png)
![image](https://user-images.githubusercontent.com/83615968/160034639-c4349613-0d81-49ad-9083-8d78326691ab.png)
![image](https://user-images.githubusercontent.com/83615968/160034695-7e3c9ef4-f795-40e7-9c77-af5efcdf676a.png)

When baking models with Cycles in the past the texture has never turned out this low res. Also, inb4 that's a lot of materials, whenever I Combine Same Materials it does this to my head 
![image](https://user-images.githubusercontent.com/83615968/160034875-092aff05-4096-4174-9970-c6e56accd6f7.png)
So texture atlasing is not my strong suit rn

**Comment by feilen** [comment]
FYI I'm splitting off Bake and a few related features into a separate plugin at https://github.com/feilen/tuxedo-blender-plugin, if you're still running into this lmk!
