### ISSUE TITLE
Bake: diffuse goes black in Blender 3.0 for no reason

### ISSUE THREAD

**Issue by g0g5** [absolute-quantum/cats-blender-plugin#400]
![image](https://user-images.githubusercontent.com/33998061/159256492-2986cc66-afeb-44d0-8b57-aa93f6ce9821.png)
![image](https://user-images.githubusercontent.com/33998061/159256578-8eb7c7ae-08d4-4848-8f48-2bfa5842439b.png)

The setting I'm using:
![image](https://user-images.githubusercontent.com/33998061/159256715-87fe2339-fb5f-40da-8df4-2e5e3611d8cb.png)
![image](https://user-images.githubusercontent.com/33998061/159256746-31804cb4-809d-4ec9-953b-6636dd9e3734.png)

I know there could be a stupid mistake hidding but I have no idea about it totally. So put a issue here and hope that's not a real bug.

**Comment by feilen** [comment]
You have 'bake to vertex colors' selected, try without it?

**Comment by g0g5** [comment]
Thanks to tell me that, I'll give a try later

**Comment by g0g5** [comment]
@feilen It doesn't work.

To be more detailed I should say that: I'm currently working on a koikatsu model with KKBP 5.1.1, following their instruction and got stuck on atlasing/ baking materials (after the intergrated baking due to it won't merge materials)
However the shader KKBP generated on model is rather complicated and tire-some, I predict it might be a problem of KKBP itself :<
