### ISSUE TITLE
Fix model error.

### ISSUE THREAD

**Issue by ShiinaRinne** [absolute-quantum/cats-blender-plugin#409]
When I use fix model, I get the following error
The model link: [https://drive.youngmoe.com/s/v7TJ](https://drive.youngmoe.com/s/v7TJ)
I used blender3, cats version is 0.9.0,  I also used 'development' branch to test, and get the same error

![image](https://user-images.githubusercontent.com/45081750/160283700-1cdaed97-3748-44ea-9674-3f5f9752d1e0.png)
![image](https://user-images.githubusercontent.com/45081750/160283712-2031c4ff-229a-4f88-aace-03dce3dffaa7.png)

Seems like China cant access google.com, I tried replacing the url directly with '.cn' in several files, but it still didn't work
![image](https://user-images.githubusercontent.com/45081750/160283337-e2dad279-5c29-4a2a-8f98-6a02b64e493a.png)

**Comment by Ruoh3kou** [comment]
try to turn off vpn

**Comment by ShiinaRinne** [comment]
> try to turn off vpn

现在没问题了，昨天应该是校园网有毛病，当时电脑直接打开translate.google.cn都不行，
开关vpn也试过，没变化
