### ISSUE TITLE
Fix Model broken - .py width error

### ISSUE THREAD

**Issue by lana53** [absolute-quantum/cats-blender-plugin#413]
![err](https://user-images.githubusercontent.com/102701051/160939804-6065c9d7-99d4-4f9c-8b98-a01ded9baa67.JPG)
![error](https://user-images.githubusercontent.com/102701051/160940247-ebfa58f9-8ee9-4e79-b13e-bb7511c36fb4.JPG)
can't update revert or fix model button

**Comment by ShasV05** [comment]
Even I'm facing this

**Comment by feilen** [comment]
This is an issue with blender 3.1, try 2.93 (for 0.19) or 3.0 (for dev)

**Comment by feilen** [comment]
Duplicate of #379.
