### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XayahBaby** [absolute-quantum/cats-blender-plugin#417]
![image](https://user-images.githubusercontent.com/102903911/161424678-7532d5b7-eb03-4cde-b5ce-467619667966.png)

It will not let me open the fix model settings and not sure how to fix it, please get back to me when you can

**Comment by VincentJonesVR** [comment]
I am experiencing the same issue.

**Comment by feilen** [comment]
This is an issue with blender 3.1, try 2.93 (for 0.19) or 3.0 (for dev)

**Comment by feilen** [comment]
Duplicate of #379.
