### ISSUE TITLE
I'm having this issue with CATS 

### ISSUE THREAD

**Issue by BenCiel12** [absolute-quantum/cats-blender-plugin#420]
![IMG_20220407_135242](https://user-images.githubusercontent.com/103207440/162250526-4c47e8db-55f1-444c-bfca-8ee586011b66.jpg)

**Comment by LaurensWeyn** [comment]
I'm having the same error. To provide some more useful information:

This can be triggered on clicking 'Fix Model', or on the spanner icon next to Fix Model, with (seemingly) any model loaded.
'Fix Model' makes some progress and eventually gives that error, wheras the spanner icon fails to load the checkbox screen it normally shows and gives the above error instead.

Blender Version: 3.1.2
CATS Version: 0.19.0

Known to work on earlier Blender versions with the same model (previously tested on Blender 2.80.0)

**Comment by 989onan** [comment]
#379

**Comment by feilen** [comment]
> #379

^
