### ISSUE TITLE
[Fix Model Settings] Not Opening (Blender 3.1.0) ~and fix~

### ISSUE THREAD

**Issue by F0xxify1** [absolute-quantum/cats-blender-plugin#424]
**Problem:**
This is the error I get with version 0.19.0 when trying to click on the Fix Model Settings in Blender 3.1.0

```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\Foxxify\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\ui\armature.py", line 205, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 3.25)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float
```

**Fix:**
Fixed by changing `dpi_value * 3.25` to `int(dpi_value * 3.25)`

**Comment by shik617** [comment]
Hi Foxxify, where can I change the "dpi_value * 3.25" ?

**Comment by bcydl0116** [comment]
> Hi Foxxify, where can I change the "dpi_value * 3.25" ?
File "C:\Users\Foxxify\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\ui\armature.py", line 205

**Comment by MyLostBear** [comment]
> Hi Foxxify, where can I change the "dpi_value * 3.25" ?


File "C:\Users\Foxxify\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\ui\armature.py", line 205

**Comment by 989onan** [comment]
Duplicate of https://github.com/absolute-quantum/cats-blender-plugin/issues/379

**Comment by evo234** [comment]
> > Hi Foxxify, where can I change the "dpi_value * 3.25" ?
> 
> File "C:\Users\Foxxify\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\ui\armature.py", line 205

what app do i get to change it??

**Comment by feilen** [comment]
> Duplicate of #379

^

**Comment by F0xxify1** [comment]
@evo234 
Make sure Blender is closed. Go to "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\ui\armature.py" or wherever your Blender appdata is stored (this is the default location).  Open the "armature.py" file with a text editor. Then you can do "CTRL+F" on Windows to find where in the document `dpi_value * 3.25` is. Then just swap it out. When you start up Blender, the issue should be resolved.

**Comment by Maul009** [comment]
(self, width=dpi_value * 3.25) to (self, width=int(dpi_value * 3.25) like that?, i change like that but i get anoter error with syntax

**Comment by KazRietveld** [comment]
> (self, width=dpi_value * 3.25) to (self, width=int(dpi_value * 3.25) like that?, i change like that but i get anoter error with syntax

(self, width=int(dpi_value * 3.25))
