### ISSUE TITLE
cannot able to click setting on fix model

### ISSUE THREAD

**Issue by xalteropsx** [absolute-quantum/cats-blender-plugin#433]
Python: Traceback (most recent call last):
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-master\ui\armature.py", line 205, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 3.25)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float

location: <unknown location>:-1

 not fixed ....

**Comment by cordade** [comment]
i'm with this too, i can't do nothing

**Comment by alertedsnake** [comment]
Ah, if you edit that line in question and wrap the parameter with `int()`, then reload Blender, it'll work fine.

**Comment by feilen** [comment]
Switch to blender 2.93, or switch to blender 3.0 with CATS dev version

**Comment by feilen** [comment]
See https://github.com/absolute-quantum/cats-blender-plugin/issues/379

**Comment by alertedsnake** [comment]
yeah too many issues with 3.0+ still when using this, I switched to 2.93 and it's been (mostly) fine.
