### ISSUE TITLE
Getting This Error while trying to export my model.

### ISSUE THREAD

**Issue by FrostyVRC** [absolute-quantum/cats-blender-plugin#437]
I was trying to export my model today, and a couple problems popped up and, I have no idea what to do, looking for help on it.

Error: 

Python: Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\tools\importer.py", line 880, in execute
    bpy.ops.cats_importer.display_error('INVOKE_DEFAULT')
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\alexs\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\tools\importer.py", line 966, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 6.1)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float

location: C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py:130

location: <unknown location>:-1

**Comment by shojoshojo** [comment]
did you find a fix?
im also having this issue.

**Comment by Crimson-S** [comment]
Im getting the same error myself

**Comment by boboshu** [comment]
me too

**Comment by ihyvon223** [comment]
I'm also getting this same error...

**Comment by Lynch3y** [comment]
same here... was work a month ago -_-'

**Comment by feilen** [comment]
Switch to blender 2.93, or switch to blender 3.0 with CATS dev version

**Comment by feilen** [comment]
See https://github.com/absolute-quantum/cats-blender-plugin/issues/379
