### ISSUE TITLE
i can never export from cats

### ISSUE THREAD

**Issue by FindingEDENxo** [absolute-quantum/cats-blender-plugin#441]
it always gives the following error
![blender_D6nLVXVhge](https://user-images.githubusercontent.com/70388842/166190667-177c4f21-619a-40c5-bbc6-ebef6a47098c.png)

**Comment by feilen** [comment]
Switch to blender 2.93, or switch to blender 3.0 with CATS dev version

**Comment by feilen** [comment]
See https://github.com/absolute-quantum/cats-blender-plugin/issues/379
