### ISSUE TITLE
Unable to Import VRMs

### ISSUE THREAD

**Issue by Bilibond** [absolute-quantum/cats-blender-plugin#445]
I haven't been able to import any VRM files. When I try I get this error message. However, I'm able to import MMD's just fine.
![Blerror](https://user-images.githubusercontent.com/104809960/166399794-c78ae0e3-8854-45b7-a6e1-db5810479343.png)
 

I have attempted to uninstall and reinstall several times. This IS my first time using Blender in general, so it may be user error.

**Comment by feilen** [comment]
Switch to blender 2.93, or switch to blender 3.0 with CATS dev version

**Comment by feilen** [comment]
See https://github.com/absolute-quantum/cats-blender-plugin/issues/379
