### ISSUE TITLE
Cats plugin not working with wrench 

### ISSUE THREAD

**Issue by LittleAqua1999** [absolute-quantum/cats-blender-plugin#463]
I been trying to get Cats plugin not working with wrench  to work i used steam and the website version and its till showing 

Python Traceback ( Most recent call last)

I'm using 0.19.0 cats and blender latest version still having issues if someone knows how to fix please help and thanks you 

![Blender cats error](https://user-images.githubusercontent.com/105766514/168954694-bc35b20c-4454-4665-ad67-57bd7ff419d5.png)

**Comment by feilen** [comment]
#379

**Comment by LittleAqua1999** [comment]
Thank you  for the information, I still haven't tried the new one I went back to an older version and it worked
