### ISSUE TITLE
Add a button to only bake shape keys

### ISSUE THREAD

**Issue by imagitama** [absolute-quantum/cats-blender-plugin#512]
Baking shape keys is a very useful feature that gives players a quick FPS boost.

To use it in CATS means you have to also bake/atlas/do heaps more optimisations when at the end of the day some people *only* want to bake their shape keys. Tested in the `development` branch in Blender 3.1.

Can you please add a button to bake the shape keys (ie find all shape keys with `_bake` suffix and bake them).

**Comment by feilen** [comment]
Should be fairly easy, don't see why not!
