### ISSUE TITLE
Python error when trying to generate twist bones (dev branch)

### ISSUE THREAD

**Issue by Svelsien** [absolute-quantum/cats-blender-plugin#540]
I'm trying to generate a twist bone for the arms and I get a python error
![image](https://user-images.githubusercontent.com/44215462/188269795-546c9f45-13b7-4997-8371-38e03c85d350.png)

(happens on blender 2.8 and 2.9)

**Comment by Mysteryem** [comment]
Looks like `use_mesh_mirror_x` was added in Blender 2.93 (https://docs.blender.org/api/2.93/change_log.html#bpy-types-object), so you would need to update your Blender version to at least 2.93 until a fix is made for older Blender versions.
