### ISSUE TITLE
Eye Tracking:  Missing section

### ISSUE THREAD

**Issue by bhoffman67** [absolute-quantum/cats-blender-plugin#544]
I have Blender 3.0.1 and Cats v0.19.1-dev installed.  I am sure v0.19 had a section for eye tracking between Decimation and Visemes but now it's no longer visible.  Where did it go??

**Comment by bhoffman67** [comment]
I guess it doesn't matter much since once it gets imported into Unity, the visemes can be set there.

**Comment by feilen** [comment]
Yeah, it's hidden by default now. Eye tracking isn't done in Blender anymore, as of Avatar 3.0

**Comment by DarthShader** [comment]
It absolutely *is* done in Blender. Eye bones need to be created from other bones, have the same orientation, and have zero bone roll. The eye tracking creation tool was perfect for doing just this, and should not have been removed.
