### ISSUE TITLE
Cats needs to be GPL v3.0 licensed to distribute mmd tools

### ISSUE THREAD

**Issue by Mysteryem** [absolute-quantum/cats-blender-plugin#550]
mmd tools is licensed GPL v3.0 since Apr 5, 2020 https://github.com/UuuNyaa/blender_mmd_tools/blob/main/LICENSE, which is a copyleft license that requires that any works that include it in distribution to be under the same license. This means that Cats must also be licensed GPL v3.0 if it is to include any of mmd tools (or any other copied or modified GPL v3.0 code) in its distribution. However, Cats is currently MIT licensed, thus violating the copyleft aspect of the GPL v3.0 license. 

There's also https://github.com/absolute-quantum/cats-blender-plugin/blob/master/tools/fbx_patch.py which is GPL v2.0 or newer and thus requires Cats to be GPL v2.0 or newer.

There shouldn't be any issues with changing Cats' license to GPL v3.0, since the existing MIT license is compatible with it. Similarly, distributing Immersive Scaler as GPL v3.0 with Cats would be fine too, since it's MIT licensed.

To quote wikipedia on GPL compatibility https://en.wikipedia.org/wiki/License_compatibility#GPL_compatibility
> Many of the most common free-software licenses, especially the [permissive licenses](https://en.wikipedia.org/wiki/Permissive_license), such as the original [MIT/X license](https://en.wikipedia.org/wiki/MIT_License), [BSD licenses](https://en.wikipedia.org/wiki/BSD_licenses) (in the three-clause and two-clause forms, though not the original four-clause form), MPL 2.0, and [LGPL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License), are GPL-compatible. **That is, their code can be combined with a program under the GPL without conflict, and the new combination would have the GPL applied to the whole (but the other license would not so apply)**.

**Comment by Darkblader24** [comment]
Done and done!
