### ISSUE TITLE
Cannot Edit "Fix Model" Settings

### ISSUE THREAD

**Issue by exocomz** [absolute-quantum/cats-blender-plugin#554]
I Get this error when trying to modify the fix model : 

Python: Traceback (most recent call last):
  File "C:\Users\shae\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\cats-blender-plugin-0-19-0\ui\armature.py", line 205, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 3.25)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float

**Comment by Geoffery10** [comment]
Where you able to find a fix for this? I'm having the same error on existing projects.

**Comment by exocomz** [comment]
> Where you able to find a fix for this? I'm having the same error on existing projects.

Yeah i found a fix, i just needed to install a previous version of Blender, i had the latest then downgraded to 2.9 and it worked
