### ISSUE TITLE
[Bake] All meshes are systematically merged

### ISSUE THREAD

**Issue by CorgiTosh** [absolute-quantum/cats-blender-plugin#581]
I am working on an avatar which needs to be able to be shirtless, or pantsless. This means different parts of the body will need to be hidden at different times (e.g the legs when the pants are on).
For this reason, it is important that I keep the different meshes separate.
![image](https://user-images.githubusercontent.com/74367079/223794998-4f9ce64c-bd77-4fd9-a434-5888fa6eb4d5.png)

However, using the baking feature will systematically group all meshes together, without the option to keep them as-is.
Is there a plan to add this option, or am I just going about this the wrong way?

**Comment by feilen** [comment]
On the Development version, there's an option to mark a mesh as a 'prop', including clothes: this moves them to separate bones parented to their original bones, so they can be inexpensively shrunk out of sight (but still with only one mesh, so the Quest is happy).

**Comment by CorgiTosh** [comment]
This is insanely useful! Thanks! Will have a look at the development version :)

**Comment by RowanSkie** [comment]
Hi, I want to do the same thing, where do I find the option to mark specific items as props?

**Comment by feilen** [comment]
FYI Bake has been moved to a new plugin: https://github.com/feilen/tuxedo-blender-plugin/
