### ISSUE TITLE
decimation_retain_separated_meshes property for Retain Separate Meshes option of decimation is missing

### ISSUE THREAD

**Issue by Mysteryem** [absolute-quantum/cats-blender-plugin#584]
From a user on discord:
```
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cats-blender-plugin-master\tools\decimation.py", line 149, in execute
    if not context.scene.decimation_retain_separated_meshes:
AttributeError: 'Scene' object has no attribute 'decimation_retain_separated_meshes'
location: <unknown location>:-1
```

The PR that added this feature https://github.com/absolute-quantum/cats-blender-plugin/pull/551
makes reference to `decimation_retain_separated_meshes`, however the PR contains no modifications to actually add a property with that name.

**Comment by CorgiTosh** [comment]
I am seeing this issue as well, and it unfortunately crashes the bakes

**Comment by Mysteryem** [comment]
Presumably fixed in https://github.com/absolute-quantum/cats-blender-plugin/commit/2f82e19e0736a6b4bdf56e19e269db4331f5eb21
