### ISSUE TITLE
Error Enabling Plugin Line 351 and 51

### ISSUE THREAD

**Issue by SlimyCat-yt** [absolute-quantum/cats-blender-plugin#657]
![20240103_145947.jpg](https://github.com/absolute-quantum/cats-blender-plugin/assets/148009697/e6dc175a-7505-403f-b0d9-501673b77d14)

[Nvm the previous edit.]

**Comment by RinaDev-xyz** [comment]
2 things.

What version of cats are you using, are you using dev or the main branch?

Second I would upgrade to a newer version of blender as cats doesn't really work well on blender 2.8 from my experience especially if your using the dev version of cats.

**Comment by SlimyCat-yt** [comment]
main branch

**Comment by RinaDev-xyz** [comment]
Ok I just downloaded that version of blender and enabled the plugin I having no issues.

Are you on Windows or Linux? and what exact version of blender are you using, i tested it on version 2.83.20.

It's possible for some reason your version of blender python modules are messed up (Like the request module cats is asking for), i do remember a version of blender where this did happen.

Therefor this is not a cats issue and is a blender issue.
