### ISSUE TITLE
DO NOT POST A NEW ISSUES READ THIS ONE FIRST!!!!!!

### ISSUE THREAD

**Issue by RinaDev-xyz** [absolute-quantum/cats-blender-plugin#670]
First of all i want to say thank you for reading this, please read fully before you post an issue. some information here is from the official discord for cats and some are from my own experiences replying on here.

**Why cat's isn't updated?**
Simply that the original owner has vanished and the community was maintaining it but no longer can, it's been a year since the last official response so at this point I think we can take it that's CATS has been abandoned. Below is the official response on the CATS discord server FAQ which was posted on the 05/04/2023.

"Due to problems beyond our control, we cannot give an estimate of when there will be an official update. This is due to many reasons, one of which is that the only reason why the addon gets any support anyways is because of the community. Because the community doesn't own the project, we cannot do anything to release an update. We can push code and update development and sometimes master, but since the owner has kind of gone on a hiatus we have no idea when or even if they will return. The owner is the only one capable of pushing a release thing that everyone loves downloading. The code thankfully is able to work without being compiled, so that is a big reason why we can happily give people the latest version without the owner's involvement. The programmers, translators, and contributors to the plugin are in the same boat.
What I can unveil is that negotiations are ongoing, and Hotox is working every day to gain the permissions to release updates and get the train rolling.
So sit back. Asking isn't gonna make it go any faster. Probably..."

**Is there an alternative to CATS?**
Yes, there are a couple, and I honestly didn't like posting my own version but at this point I getting annoyed at repeating myself so here you go.

- You can get my UN-OFFICIAL VERSION. Please note this version IS NOT RELATED TO THE OFFICIAL VERSION so please do not ask for help in the official cats discord if you are using my version. My version contains several fixes and improvements and has a version for 4.0: https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-
- If you want Cats Decimation, bake and some other optimizations which cats used to have, use Tuxedo, it's a fantastic alternative to cats old bake feature: https://github.com/feilen/tuxedo-blender-plugin
- You can get material combiner here: https://github.com/Grim-es/material-combiner-addon

You can also look at the forks, though there doesn't seem to be any forks which keep cats as maintained as my version though.

**I don't want to use the non-official one though?**
That's fine however follow this advice to get the official one working on newer blender versions.

DON'T USE THE MAIN BRANCH OR RELEASED VERSION OF CATS FOR BLENDER 3.1+ USE THE DEV VERSION!!!!!!!! 
DON'T USE BLENDER 4.0 THE OFFICIAL VERSION OF CATS ISN'T UPDATED TO USE NEW API CHANGES AND MMD TOOLS HAS NOT BEEN UPDATED TO 4.0!

You can find the dev version here: https://github.com/absolute-quantum/cats-blender-plugin/tree/development
Direct zip download: https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip

The best version of blender to use is either 3.5 or 3.6 (You may get some warnings on 3.6 but it seems to work just fine).

**I get this issue below:**

![1](https://github.com/absolute-quantum/cats-blender-plugin/assets/104736380/656e68e5-ddac-4fee-ac21-45edc0d9161e)

Did you even read what I said? 
DON'T USE THE MAIN BRANCH OR RELEASED VERSION OF CATS FOR BLENDER 3.1+ USE THE DEV VERSION!!!!!!!! 

**Why can't I use the main branch on blender 3.1+?**
Because the main branch has not been updated in years and does not contain the many fixes and improvements the dev branch has for these versions of blender.

**Why can't I use blender 4.0+?**
Blender 4.0 has quite a few API changes which breaks some functions in CATS and MMD Tools. You will find certain functions like the Fix Model button and some other functions will give you errors. This will only get worse with Blender 4.1 and more as blender is changing alot of behind the scenes stuff. Therefor even though Cats semi works on 4.0 from 4.1 Cats will most likely completely break.

**You keep talking about these MMD Tools what is this?**
MMD Tools is a 3rd party plugin which cats uses for several things, including importing mmd/vrm stuff and etc, it's a key component of cats and several features would not work without. Hence CATS is reliant on MMD Tools to be updated for cats to work 100%. 

As more frequent questions come in, I will update this, if the above hasn't answered your question then post an issue, HOWEVER don't expect anyone to answer as again this github has basically been abandoned at this point.

**But I must have the official version for blender 4.0?**

If you MUST have the official cats work on blender 4.0 (Even though I done all the work for you and more on my version) then you can try to apply the changes from pull request #648 to the dev version of cats. DON'T USE ANY OTHER PULL REQUEST AS MOST ARE FOR THE MAIN BRANCH AND DO NOT USE AN RELEASED VERSION OR MAIN BRANCH OF CATS.

You can then also download and manually update cats version of MMD tools as well, to update MMD tools you can do the following.

- Delete mmd_tools_local folder in extern_tools folder.
- Paste updated mmd_tools folder into root of project
- Refactor folder name "mmd_tools" to "mmd_tools_local" and update all references in all files for MMD Tools.
- Move mmd_tools_local folder into extern_tools folder
- Search for "show_backface_culling" and set it to False in view.py
- Done

Do not use the main branch for 4.0, you will find more and more issues on the main branch which are fixed in the dev version.

**Comment by CallMeRyu** [comment]
Have you been looking in  https://github.com/absolute-quantum/cats-blender-plugin/pulls too?

**Comment by instanramen** [comment]
so i have to downgrade my blender?

**Comment by RinaDev-xyz** [comment]
Read everything before asking a question, your answer is in there.

But in short yes, you won't be able to fully use blender 4.0+ properly with this version of cats due to MMD Tools issues.

**Comment by RinaDev-xyz** [comment]
Old version closed, please see this one: https://github.com/absolute-quantum/cats-blender-plugin/issues/687
