### ISSUE TITLE
idk why but everytime i want to activate cats a error appears

### ISSUE THREAD

**Issue by ozan101** [absolute-quantum/cats-blender-plugin#675]
![Screenshot 2024-04-21 190648](https://github.com/absolute-quantum/cats-blender-plugin/assets/126927284/bab0f129-e91e-400d-8901-f985a6f87355)

The error:

Traceback (most recent call last):

File E/Steam Library/steamapps/common/Blender/4.1/scripts/modules/addon_utils.py , line 444 enable

bpy.context.window_amanger.addon_support = (OFFICIAL, COMMUNITY, TEXTING)

ValueError:bpy_struct: item.attr = val:: TESTING not found in (OFFICIAL COMMUNITY)

**Comment by ozan101** [comment]
> ![Screenshot 2024-04-21 190648](https://private-user-images.githubusercontent.com/126927284/324265226-bab0f129-e91e-400d-8901-f985a6f87355.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MTk3NTQsIm5iZiI6MTcxMzcxOTQ1NCwicGF0aCI6Ii8xMjY5MjcyODQvMzI0MjY1MjI2LWJhYjBmMTI5LWU5MWUtNDAwZC04OTAxLWY5ODVhNmY4NzM1NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQxNzEwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2ZkZmZhMjRjYzJlOTM5ODViYzE3NmExYzRhMTUwNTk1ZTUzYzgyOTM4MDY1MmNhNzY4MWY5M2MzNjFiYzJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TUpgkaTOSAC1Cisck7tpv2nJ8m1_Gk9fzcE1ZrSM3UA)
> 
> The error:
> 
> Traceback (most recent call last):
> 
> File E/Steam Library/steamapps/common/Blender/4.1/scripts/modules/addon_utils.py , line 444 enable
> 
> bpy.context.window_amanger.addon_support = (OFFICIAL, COMMUNITY, TEXTING)
> 
> ValueError:bpy_struct: item.attr = val:: TESTING not found in (OFFICIAL COMMUNITY)

**Comment by ozan101** [comment]
i fixed it

**Comment by githubuser47398472398472398** [comment]
can you pls tell how you did this?
