### ISSUE TITLE
Blender 4.2 install has python error

### ISSUE THREAD

**Issue by manzhizhen** [absolute-quantum/cats-blender-plugin#688]
My windows download the cats-blender-plugin-master.zip file，and use Blender 4.2 to install it, but I get this error: 
![image](https://github.com/user-attachments/assets/b7e697a8-b292-47b3-be3a-7677a5f339cf)

This is my python version and numpy version:
C:\Users\manzh>python --version
Python 3.10.6

C:\Users\manzh>pip install numpy
Requirement already satisfied: numpy in c:\users\manzh\appdata\local\programs\python\python38\lib\site-packages (1.23.0)

[notice] A new release of pip is available: 23.3.2 -> 24.2
[notice] To update, run: c:\users\manzh\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip

I guess is my python version problem ?

**Comment by RinaDev-xyz** [comment]
So you ignored my post which states: "READ FIRST PLEASE - THIS GITHUB IS NOT MONITORED BY ANYONE SO DON'T BOTHER POSTING AN ISSUES, READ THIS INSTEAD!" which answers your question?

Please read this post and close your issue: https://github.com/absolute-quantum/cats-blender-plugin/issues/687 
Wrong cats version for your blender version.
